jobs:
- job: distribution
  displayName: Distribution
  pool:
    type: windows
  variables:
    ob_outputDirectory: $(Build.SourcesDirectory)\artifacts\dist
  steps:
  - checkout: self
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_build_windows_schannel_Release
      path: $(Build.SourcesDirectory)\artifacts\bin\windows
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_build_windows_openssl_Release
      path: $(Build.SourcesDirectory)\artifacts\bin\windows

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_build_windows_schannel_Debug
      path: $(Build.SourcesDirectory)\artifacts\bin\windows
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_build_windows_openssl_Debug
      path: $(Build.SourcesDirectory)\artifacts\bin\windows

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_build_UWP_schannel_Release
      path: $(Build.SourcesDirectory)\artifacts\bin\uwp
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_build_UWP_openssl_Release
      path: $(Build.SourcesDirectory)\artifacts\bin\uwp

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_build_UWP_schannel_Debug
      path: $(Build.SourcesDirectory)\artifacts\bin\uwp
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: drop_build_build_UWP_openssl_Debug
      path: $(Build.SourcesDirectory)\artifacts\bin\uwp

  - task: PowerShell@2
    displayName: Distribution
    inputs:
      pwsh: false
      filePath: scripts/package-distribution.ps1
